# Generated by Django 4.2 on 2024-10-13 10:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_commentmodel_user_name_commentmodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='name', max_length=300, null=True)),
                ('age', models.IntegerField(blank=True, db_column='age', null=True)),
                ('uage', models.CharField(choices=[('year', 'year'), ('month', 'month'), ('day', 'day')], db_column='uage', max_length=100)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Famle', 'Famle')], db_column='sex', max_length=300)),
                ('drname', models.CharField(blank=True, db_column='drname', max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imgBarcode', models.ImageField(blank=True, upload_to='uploads/barcode/')),
                ('idBarcode', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'db_table': 'patient',
            },
        ),
    ]
