# Generated by Django 4.2 on 2024-10-13 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_patient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={},
        ),
        migrations.AlterModelTable(
            name='patient',
            table=None,
        ),
    ]
