# Generated by Django 4.2 on 2024-10-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_patient_options_alter_patient_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='idBarcode',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
