# Generated by Django 4.2 on 2024-10-13 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_patient_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likemodel',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient'),
        ),
    ]
