# Generated by Django 4.2 on 2024-10-14 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_likemodel_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient'),
        ),
    ]
