# Generated by Django 4.2 on 2024-10-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_commentmodel_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apprvname', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(choices=[('Hematology', 'Hematology'), ('Chemistry', 'Chemistry'), ('bacteriology', 'bacteriology'), ('Imuntology', 'Imuntology'), ('parasitology', 'parasitology')], max_length=100)),
                ('categorySpecific', models.CharField(blank=True, max_length=100, null=True)),
                ('sample', models.CharField(choices=[('EDTA', 'EDTA'), ('Serum', 'Serum'), ('Plasma sodium citrate ', 'Plasma sodium citrate'), ('CSF fluid', 'CSF fluid'), ('Urine', 'Urine'), ('Stool', 'Stool')], max_length=100)),
                ('parent', models.CharField(choices=[('1', '1'), ('0', '0')], max_length=10)),
                ('price', models.FloatField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('active', models.CharField(choices=[('1', '1'), ('0', '0')], max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
