# Generated by Django 4.2 on 2024-10-16 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_resultmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='idBarcode',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='resultmodel',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient', to_field='idBarcode'),
        ),
    ]
