# Generated by Django 4.2 on 2024-10-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_patient_idbarcode_alter_resultmodel_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='notSingle',
            field=models.CharField(choices=[('1', '1'), ('0', '0')], default=0, max_length=10),
        ),
    ]
