# Generated by Django 4.2 on 2024-10-19 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_test_notsingle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultmodel',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.test'),
        ),
    ]
