# Generated by Django 4.2 on 2024-10-19 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_resultmodel_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultmodel',
            old_name='category',
            new_name='autherresult',
        ),
    ]
