# Generated by Django 4.2 on 2024-10-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_category_resultmodel_autherresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='notSingle',
        ),
        migrations.AddField(
            model_name='test',
            name='testSingle',
            field=models.BooleanField(default=False),
        ),
    ]
