# Generated by Django 4.2 on 2024-10-23 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0020_remove_test_notsingle_test_testsingle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WBC', models.CharField(blank=True, max_length=100, null=True)),
                ('GRN', models.CharField(blank=True, max_length=100, null=True)),
                ('LYM', models.CharField(blank=True, max_length=100, null=True)),
                ('MID', models.CharField(blank=True, max_length=100, null=True)),
                ('GRN_per', models.CharField(blank=True, max_length=100, null=True)),
                ('LYM_per', models.CharField(blank=True, max_length=100, null=True)),
                ('MID_per', models.CharField(blank=True, max_length=100, null=True)),
                ('RBC', models.CharField(blank=True, max_length=100, null=True)),
                ('HGB', models.CharField(blank=True, max_length=100, null=True)),
                ('HCT', models.CharField(blank=True, max_length=100, null=True)),
                ('MCV', models.CharField(blank=True, max_length=100, null=True)),
                ('MCH', models.CharField(blank=True, max_length=100, null=True)),
                ('MCHC', models.CharField(blank=True, max_length=100, null=True)),
                ('PLT', models.CharField(blank=True, max_length=100, null=True)),
                ('MPV', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient', to_field='idBarcode')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
