# Generated by Django 4.2 on 2024-10-23 07:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0022_remove_cbc_blog_cbc_idbarcode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CBC',
            new_name='CBCModel',
        ),
    ]
